# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addToCart(self):
    self.setup_method(None)
    self.driver.get("https://www.demoblaze.com/")
    self.driver.set_window_size(699, 768)
    self.driver.execute_script("window.scrollTo(0,367)")
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-4:nth-child(1) .card-img-top").click()
    self.driver.find_element(By.LINK_TEXT, "Add to cart").click()
    assert self.driver.switch_to.alert.text == "Product added"
    self.driver.find_element(By.ID, "cartur").click()
    self.driver.find_element(By.CSS_SELECTOR, "td > img").click()
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(2)").click()
    self.driver.find_element(By.LINK_TEXT, "Delete").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-1 > h2").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-1 > h2").click()
    self.driver.close()
  
  def test_browse(self):
    self.setup_method(None)
    self.driver.get("https://www.demoblaze.com/")
    self.driver.set_window_size(699, 768)
    self.driver.execute_script("window.scrollTo(0,203)")
    self.driver.find_element(By.ID, "itemc").click()
    self.driver.find_element(By.LINK_TEXT, "Laptops").click()
    self.driver.find_element(By.LINK_TEXT, "Monitors").click()
    self.driver.close()

  def test_explore(self):
    self.setup_method(None)
    self.driver.get("https://www.demoblaze.com/")
    self.driver.set_window_size(699, 768)
    self.driver.find_element(By.LINK_TEXT, "Contact").click()
    self.driver.find_element(By.CSS_SELECTOR, "#exampleModal .btn-secondary").click()
    self.driver.find_element(By.LINK_TEXT, "About us").click()
    self.driver.find_element(By.CSS_SELECTOR, "#videoModal .btn").click()
    self.driver.find_element(By.ID, "cartur").click()
    self.driver.find_element(By.ID, "login2").click()
    self.driver.find_element(By.CSS_SELECTOR, "#logInModal .btn-secondary").click()
    self.driver.find_element(By.ID, "signin2").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#signInModal .btn-secondary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#signInModal .btn-secondary").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.close()

  def test_verify(self):
    self.setup_method(None)
    self.driver.get("https://www.demoblaze.com/")
    self.driver.set_window_size(699, 768)
    self.driver.find_element(By.ID, "itemc").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-4:nth-child(1) .card-img-top").click()
    self.driver.find_element(By.LINK_TEXT, "Add to cart").click()
    assert self.driver.switch_to.alert.text == "Product added"
    self.driver.find_element(By.ID, "cartur").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    self.driver.execute_script("window.scrollTo(0,195)")
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("Mohamed Ali Selmi")
    self.driver.find_element(By.ID, "country").send_keys("Tunisia")
    self.driver.find_element(By.ID, "city").send_keys("Kairouan")
    self.driver.find_element(By.ID, "card").click()
    self.driver.find_element(By.ID, "card").send_keys("1231654987")
    self.driver.find_element(By.ID, "month").click()
    self.driver.find_element(By.ID, "month").send_keys("12")
    self.driver.find_element(By.ID, "year").click()
    self.driver.find_element(By.ID, "year").send_keys("26")
    self.driver.find_element(By.ID, "year").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".vsc-initialized").click()
    self.driver.find_element(By.CSS_SELECTOR, "#orderModal .btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".confirm").click()
    self.driver.close()
    
test = Test()
test.test_addToCart()
test.test_browse()
test.test_explore()
test.test_verify()