# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestExercise1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_exercise1(self):
    self.setup_method(None)
    self.driver.get("https://safatelli.github.io/tp-test-logiciel/assets/hello.html")
    self.driver.set_window_size(699, 768)
    self.driver.find_element(By.ID, "username").click()
    print("Entering 'dali' into the username field")
    self.driver.find_element(By.ID, "username").send_keys("dali")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    assert self.driver.find_element(By.ID, "message").text == "Bonjour, dali !", print("test 2 failed ❌")
    print("test 1 passed ✅")

    self.driver.find_element(By.ID, "username").clear()
    
    print("Entering 'dali selmi' into the username field")
    self.driver.find_element(By.ID, "username").send_keys("dali selmi")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    assert self.driver.find_element(By.ID, "message").text == "Bonjour, dali selmi !", print("test 2 failed ❌")
    print("test 2 passed ✅")
    self.driver.close()
  

print("test Exercise 1 starting...")
test = TestExercise1()
test.test_exercise1()
print("test Exercise 1 passed ✅")