# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAdd():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_add(self):
    print("Testing addition...")
    self.setup_method(None)
    self.driver.get("https://safatelli.github.io/tp-test-logiciel/assets/calc.html")
    self.driver.set_window_size(699, 768)
    self.driver.find_element(By.ID, "num1").send_keys("1")
    self.driver.find_element(By.ID, "operator").click()
    dropdown = self.driver.find_element(By.ID, "operator")
    dropdown.find_element(By.XPATH, "//option[. = '+']").click()
    self.driver.find_element(By.ID, "num2").send_keys("2")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    assert self.driver.find_element(By.ID, "result").text == "Résultat : 3", print("test failed ❌")
    print("test passed ✅")
    self.driver.close()

  def test_multi(self):
    print("🧪 test multiplication...")
    self.setup_method(None)
    self.driver.get("https://safatelli.github.io/tp-test-logiciel/assets/calc.html")
    self.driver.set_window_size(699, 768)
    self.driver.find_element(By.ID, "num1").send_keys("3")
    self.driver.find_element(By.ID, "operator").click()
    dropdown = self.driver.find_element(By.ID, "operator")
    dropdown.find_element(By.XPATH, "//option[. = '*']").click()
    self.driver.find_element(By.ID, "num2").send_keys("2")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    assert self.driver.find_element(By.ID, "result").text == "Résultat : 6", print("test failed ❌")
    print("test passed ✅")
    print("--------------------------------")
    self.driver.close()

  def test_div(self):
    print("🧪 test division...")
    self.setup_method(None)
    self.driver.get("https://safatelli.github.io/tp-test-logiciel/assets/calc.html")
    self.driver.set_window_size(699, 768)
    self.driver.find_element(By.ID, "num1").send_keys("10")
    self.driver.find_element(By.ID, "operator").click()
    dropdown = self.driver.find_element(By.ID, "operator")
    dropdown.find_element(By.XPATH, "//option[. = '/']").click()
    self.driver.find_element(By.ID, "num2").send_keys("2")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    assert self.driver.find_element(By.ID, "result").text == "Résultat : 5", print("test failed ❌")
    print("test passed ✅")
    print("--------------------------------")
    self.driver.close()

  def test_sub(self):
    print("🧪 test subtraction...")
    self.setup_method(None)
    self.driver.get("https://safatelli.github.io/tp-test-logiciel/assets/calc.html")
    self.driver.set_window_size(699, 768)
    self.driver.find_element(By.ID, "num1").send_keys("3")
    self.driver.find_element(By.ID, "operator").click()
    dropdown = self.driver.find_element(By.ID, "operator")
    dropdown.find_element(By.XPATH, "//option[. = '-']").click()
    self.driver.find_element(By.ID, "num2").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    assert self.driver.find_element(By.ID, "result").text == "Résultat : 2", print("test failed ❌")
    print("test passed ✅")
    print("--------------------------------")
    self.driver.close()

  def test_div_by_zero(self):
    print("🧪 test division by zero...")
    self.setup_method(None)
    self.driver.get("https://safatelli.github.io/tp-test-logiciel/assets/calc.html")
    self.driver.set_window_size(699, 768)
    self.driver.find_element(By.ID, "num1").send_keys("3")
    self.driver.find_element(By.ID, "operator").click()
    dropdown = self.driver.find_element(By.ID, "operator")
    dropdown.find_element(By.XPATH, "//option[. = '/']").click()
    self.driver.find_element(By.ID, "num2").send_keys("0")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    assert self.driver.find_element(By.ID, "result").text == "Résultat : Infinity", print("test failed ❌")
    print("test passed ✅")
    print("--------------------------------")
    self.driver.close()
  
test = TestAdd()
test.test_add()
test.test_multi()
test.test_div()
test.test_sub()
